@echo off
title SIC-Fast is running... [Setting up]
cd 
set /a startTime=%TIME%
color 03
mode con: cols=75 lines=7
set /a rand=%random%
set /a time=%time%
set /a date=%date%
set lol=output-%username%-%computername%-%time%_%date%_%rand%-SIC-Fast
title SIC-Fast is running... [Getting info]
echo [SIC-Fast] Running... [Mode=1, format=folder (.txt, .xml), PC-user=%username%]
echo [SIC-Fast] filename: %lol%
echo [SIC-Fast] This should take around 10 sec
echo PC Name: %computername%>output.txt
echo Made in: %TIME% %DATE%>>output.txt
echo Java: %JAVA_HOME%>>output.txt
echo Home drive: %homedrive%>>output.txt
:start
echo -_-_-_-_-_-_- COMPUTER INFO -_-_-_-_-_-_->>output.txt
systeminfo>>output.txt
echo -_-_-_-_-_-_- WIFI INFO -_-_-_-_-_-_->>output.txt
ipconfig>>output.txt
echo -_-_-_-_-_-_- PING -_-_-_-_-_-_->>output.txt
ping google.com>>output.txt
echo -_-_-_-_-_-_- CPU -_-_-_-_-_-_->>output.txt
wmic cpu|more>>output.txt
echo -_-_-_-_-_-_- RAM -_-_-_-_-_-_->>output.txt
wmic MEMORYCHIP get BankLabel, DeviceLocator, Capacity, Speed|more>>output.txt
echo -_-_-_-_-_-_- OS -_-_-_-_-_-_->>output.txt
wmic os|more>>output.txt
echo -_-_-_-_-_-_- DISKS 1 -_-_-_-_-_-_->>output.txt
wmic diskdrive get model,size|more>>output.txt
echo -_-_-_-_-_-_- SOUND -_-_-_-_-_-_->>output.txt
wmic sounddev get Caption|more>>output.txt
echo -_-_-_-_-_-_- POWER PLAN -_-_-_-_-_-_->>output.txt
powercfg /L>>output.txt
echo -_-_-_-_-_-_- TASKLIST -_-_-_-_-_-_->>output.txt
tasklist>>output.txt
echo -_-_-_-_-_-_- GRAPHICS CARD -_-_-_-_-_-_->>output.txt
wmic path win32_VideoController get name|more>>output.txt
echo -_-_-_-_-_-_- History -_-_-_-_-_-_->>output.txt
ipconfig /displaydns >>output.txt
echo  WIFI PASSWORDS (in .xml format)>>output.txt
title SIC-Fast is running... [Exporting to folder]

echo [SIC-Fast] Done
color 20

mkdir "\Outputy SIC-Fast\%lol%"
netsh wlan export profile key=clear folder="\Outputy SIC-Fast\%lol%"


:end
title SIC-Fast - Done :)
title SIC-Fast is running... [Finished]
set /a endTime=%TIME%
echo Started at %startTime% and ended at %endTime%.>>output.txt
echo This output file was generated by SIC-Fast v0.7 made by Plawro.>>output.txt
copy output.txt "\Outputy SIC-Fast\%lol%\%lol%.txt" >nul
del output.txt
exit